services:
  - type: worker
    name: telegram-file-store-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DATABASE_NAME
        value: telegram_file_store
